# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1c573756fecc4841176ec302a69f12ec158f3890d7b76ead00a5505941f2454e538027a1a0fa63e436ff6ec62b442db91a48d7d22fca7a006227dbf6403ac6e

test:
  secret_key_base: b690e0eace136d382ed74619a4d17d860f827d625ab65d5af2baf9c82da47dd0d6532c0382625b22a3192ecce1e1040d7deb84de4cbfbc35d16d29710728ba0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
